# Generated by Django 5.2.5 on 2025-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
